/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallState {
  'isActive' : boolean,
  'callee' : Principal,
  'caller' : Principal,
}
export interface ConnectionRequest {
  'requester' : Principal,
  'target' : Principal,
  'timestamp' : Time,
}
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'username' : Username,
  'displayName' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptCall' : ActorMethod<[Principal], undefined>,
  'acceptConnectionRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineCall' : ActorMethod<[Principal], undefined>,
  'endCall' : ActorMethod<[Principal], undefined>,
  'getCallState' : ActorMethod<[], [] | [CallState]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConnections' : ActorMethod<[], Array<Principal>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getPendingRequests' : ActorMethod<[], Array<ConnectionRequest>>,
  'getUserByUsername' : ActorMethod<[Username], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initiateCall' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'onboard' : ActorMethod<[string, string, string], UserProfile>,
  'rejectConnectionRequest' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendConnectionRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];