/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CallState = IDL.Record({
  'isActive' : IDL.Bool,
  'callee' : IDL.Principal,
  'caller' : IDL.Principal,
});
export const Username = IDL.Text;
export const UserProfile = IDL.Record({
  'username' : Username,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const ConnectionRequest = IDL.Record({
  'requester' : IDL.Principal,
  'target' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptCall' : IDL.Func([IDL.Principal], [], []),
  'acceptConnectionRequest' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'declineCall' : IDL.Func([IDL.Principal], [], []),
  'endCall' : IDL.Func([IDL.Principal], [], []),
  'getCallState' : IDL.Func([], [IDL.Opt(CallState)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(ConnectionRequest)], ['query']),
  'getUserByUsername' : IDL.Func([Username], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initiateCall' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'onboard' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [UserProfile], []),
  'rejectConnectionRequest' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendConnectionRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CallState = IDL.Record({
    'isActive' : IDL.Bool,
    'callee' : IDL.Principal,
    'caller' : IDL.Principal,
  });
  const Username = IDL.Text;
  const UserProfile = IDL.Record({
    'username' : Username,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const ConnectionRequest = IDL.Record({
    'requester' : IDL.Principal,
    'target' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptCall' : IDL.Func([IDL.Principal], [], []),
    'acceptConnectionRequest' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'declineCall' : IDL.Func([IDL.Principal], [], []),
    'endCall' : IDL.Func([IDL.Principal], [], []),
    'getCallState' : IDL.Func([], [IDL.Opt(CallState)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getPendingRequests' : IDL.Func(
        [],
        [IDL.Vec(ConnectionRequest)],
        ['query'],
      ),
    'getUserByUsername' : IDL.Func(
        [Username],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initiateCall' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'onboard' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [UserProfile], []),
    'rejectConnectionRequest' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendConnectionRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };